# Generated by Django 3.2.6 on 2021-08-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key1',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='key2',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='key3',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
