# Generated by Django 3.2.6 on 2021-08-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20210824_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key1',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='key2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='key3',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
