# Generated by Django 3.2.6 on 2021-08-24 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20210824_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='key1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='key2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='key3',
        ),
    ]
