# Generated by Django 3.2.6 on 2021-08-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20210824_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='key3',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='key4',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='key5',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
