# Generated by Django 3.2.6 on 2021-08-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20210824_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key1',
            field=models.CharField(default='', max_length=255),
        ),
    ]
