# Generated by Django 3.2.6 on 2021-08-24 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.room'),
        ),
    ]
