# Generated by Django 3.2.6 on 2021-08-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_file_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
