# Generated by Django 3.2.6 on 2021-08-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_user_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='part',
        ),
        migrations.AddField(
            model_name='user',
            name='book',
            field=models.ManyToManyField(blank=True, to='application.Room'),
        ),
    ]
