# Generated by Django 3.2.6 on 2021-08-26 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_auto_20210827_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
